### ISSUE TITLE
CONFIG_RQ_LLC is not found

### ISSUE THREAD

**Issue by zhmars** [jiblime/clear-ck-gentoo-sources#1]
Hi, I can't find any `CONFIG_RQ_LLC` setting, only `CONFIG_RQ_MC_LLC`. typo?

**Comment by jiblime** [comment]
You're right, typo. Thanks!

It's still a bit messy and I haven't pushed some changes I've made to remote. If you see anything that might be incorrect or outdated feel free to open an issue or PR :)
